### ISSUE TITLE
D4 und C12 sind unklar

### ISSUE THREAD

**Issue by Hiwados** [skunkforce/c002_magjack_with_PoE_PD_flyback#2]
Bei diesen beiden Bauteile habe ich keine genauen Information gefunden, bezüglich der Diode fehlt mir die MPN damit ich weiß wofür Sie ausgelegt sein soll. Und bei C12 fehlen mir angaben zur Toleranz und Spannungsfestigkeit.

**Comment by NP199** [comment]
@odinthenerd

**Comment by odinthenerd** [comment]
C12 angaben sind im schemetic zu finden

D4 angaben sind verbessert
